//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cuidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cuidad()
        {
            this.tbl_cliente = new HashSet<tbl_cliente>();
        }
    
        public int idciudad { get; set; }
        public string nombreciudad { get; set; }
        public string tamano { get; set; }
        public string indice { get; set; }
        public string ingreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cliente> tbl_cliente { get; set; }
    }
}
