//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Beta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [Required]
        [Display(Name = "Id Usuario")]
        public long idUsuario { get; set; }
        [Required]
        [Display(Name = "Usuario")]
        public string usuario { get; set; }
        [Required]
        [Display(Name = "Contrasena")]
        public string contrasena { get; set; }
        [Required]
        [Display(Name = "Email")]
        public string email { get; set; }
        [Required]
        [Display(Name = "Telefono")]
        public Nullable<long> telefono { get; set; }
    }
}
